name: Infrastructure deployment in Azure through Terraform

on:
  workflow_call:
    inputs:
      gh-env: 
        required: true
        type: string
      gh-runner:
        type: string
        default: 'ubuntu-latest'
      tf-module-name:
        required: true
        type: string
      tf-module-version:
        required: true
        type: string
      tf-module-storage-container:
        type: string
        default: 'tf-modules'
      tfvars-directory:
        required: true
        type: string
      tf-module-version-file:
        type: string
        default: 'version.json'
      

jobs:

  tf-plan:
    name: Terraform Plan
    environment: ${{ inputs.gh-env }}
    runs-on: ${{ inputs.gh-runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Artifact Directory
        run: mkdir ${{ runner.temp }}/terraform_artifact
      - name: Copy Tfvars
        run: cp ${{ github.workspace }}/${{ inputs.tf-module-name }}/${{ inputs.tfvars-directory }}/* ${{ runner.temp }}/terraform_artifact
      - name: Download Module
        uses: fixpoint/azblob-download-artifact@v3
        with:
          connection-string: ${{ secrets.TF_MODULE_STORAGE_ACCOUNT_CONNECTION_STRING }}
          name: ${{ inputs.tf-module-name }}
          container: ${{ inputs.tf-module-storage-container }}
      - name: Unzip module
        run: unzip ${{ github.workspace }}/${{ inputs.tf-module-name }}/${{ inputs.tf-module-version }}.zip -d ${{ runner.temp }}/terraform_artifact/
      - name: List artifacts
        run: ls -ltr ${{ runner.temp }}/terraform_artifact/
      - name: Setup Backend
        run: |
          echo "terraform {
            backend "azurerm" {}
          }" >> ${{ runner.temp }}/terraform_artifact/backend.tf
      - name: Set Deployment Info
        run: |
          echo "deployment_info = {'repo-name':'${{ github.repository }}'}" >> ${{ runner.temp }}/terraform_artifact/deployment-info.auto.tfvars
      - name: Set terraform version
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: ${{ runner.temp }}/terraform_artifact//${{ inputs.tf-module-version-file }}
          prefix: json-var
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.json-var_tf-version }}
