name: Infrastructure module release

on:
  workflow_call:
    inputs:
      tf-module-name:
        required: true
        type: string
      gh-env:
        type: string
        default: 'tf-module-release'
      gh-runner:
        type: string
        default: 'ubuntu-latest'
      tf-module-version-file:
        type: string
        default: 'version.json'
jobs:

  tf-module-release:
    name: Release ${{ inputs.tf-module-name }}
    environment: ${{ inputs.gh-env }}
    runs-on: ${{ inputs.gh-runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set module version
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: ${{ github.workspace }}/${{ inputs.tf-module-name }}/${{ inputs.tf-module-version-file }}
          prefix: json-var
      - name: Generate Artifact
        uses: TheDoctor0/zip-release@0.6.2
        with:
          filename: ${{ inputs.tf-module-name }}/${{ env.json-var_module-version }}.zip
          path: ${{ github.workspace }}/${{ inputs.tf-module-name }}
      - name: Upload Artifact
        uses: fixpoint/azblob-upload-artifact@v4
        with:
          connection-string: ${{ secrets.TF_MODULE_STORAGE_ACCOUNT_CONNECTION_STRING }}
          name: ${{ github.repository }}/${{ inputs.tf-module-name }}
          path: ${{ github.workspace }}/${{ inputs.tf-module-name }}/${{ env.json-var_module-version }}.zip
          container: tf-modules
      - name: Create GitHub Tag
        uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          version: ${{ env.json-var_module-version }}
          git_tag_prefix: ${{ inputs.tf-module-name }}-v
